### ISSUE TITLE
Site is not up.

### ISSUE THREAD

**Issue by Haroenv** [tomspeak/pomodo.work#7]
I guess that's pretty much all there is to say. That's pretty straight-forward.

**Comment by M4urice** [comment]
Still down.

**Comment by raphaelm** [comment]
You need to adjust ``app-routers.js``. I set up a working instance at https://raphaelm.github.io/pomodo.io/

**Comment by tomspeak** [comment]
v2.0.0 is now available: http://pomodo.work
